name: JS / TS Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-functions:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: functions

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm install

      - name: Run Jest with coverage (CI mode)
        run: npm test -- --coverage
