jobs:
  build-and-test:
    runs-on: macos-latest

    defaults:
      run:
        working-directory: app

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: |
          xcodebuild \
            -project PartnerAndPump.xcodeproj \
            -scheme PartnerAndPump \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            build

      - name: Test
        run: |
          xcodebuild \
            -project PartnerAndPump.xcodeproj \
            -scheme PartnerAndPump \
            -destination 'platform=iOS Simulator,name=iPhone 15' \
            test
